name: CI + Security Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
    #checkout
    - name: Checkout code
      uses: actions/checkout@v4

    #setup node
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Initialize DB
      run: npm run init-db

    #sast
    - name: SAST - Scan for secrets
      run: |
        echo "Scanning for secrets..."
        if grep -r "API_KEY=" .; then
          echo "Hardcoded secret found!"
          exit 1
        else
          echo "No secrets found"
        fi


    #wait for deployment input
    - name: Set target URL
      run: echo "TARGET_URL=${{ secrets.TARGET_URL }}" >> $GITHUB_ENV

    #dast using owasp zap
    - name: Run OWASP ZAP Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: ${{ env.TARGET_URL }}